# Generated by Django 2.1 on 2018-08-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
