# Generated by Django 2.1 on 2018-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0002_delete_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
