# Generated by Django 2.1 on 2018-08-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0004_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
